# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gauge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BLGaugeView', :git => 'https://github.com/brunolimam/BLGaugeView.git', :branch => 'master'

  # Pods for Gauge

  target 'GaugeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GaugeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
